services:
  bot:
    ports:
      - "5678:5678"
      - "7900:7900"
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "-m", "gmeetbot"]
