services:
  bot:
    env_file:
      - .env
    container_name: gmeet_bot
    ports:
      - 12396:8080
      - 12390:7900
    build:
      context: .
    volumes:
      - video_data:/app/videos

volumes:
  video_data:
